"""
Accessibility Control -- SEAM ONLY, NOT IMPLEMENTED IN THIS MVP
===================================================================
This module is the intended home for a future `AccessibilityUIController`
implementing `core.interfaces.IUIController` (app-level automation:
"Open Telegram, search Asad, write Hello"). Per the current project
scope ("ignore complex Automation" for this phase), it is NOT built
out yet -- but the seam is wired so adding it later is additive only.

WHY THIS CAN'T BE PURE PYTHON:
Android requires an actual Java (or Kotlin) class extending
`android.accessibilityservice.AccessibilityService`, declared in
AndroidManifest.xml with the `android.permission.BIND_ACCESSIBILITY_SERVICE`
permission and an `accessibility_service_config.xml` resource
describing which events it wants (window content changes, etc). This
cannot be generated by python-for-android's normal Python-only build --
it requires adding real Java source via `android.add_src` in
buildozer.spec, and the resulting service still communicates with our
Python process via a local broadcast/socket bridge, since
AccessibilityService callbacks fire on Java's side.

Additionally, Android does NOT allow an app to silently enable its own
accessibility service (this is a deliberate anti-malware protection) --
the user must open Settings > Accessibility and toggle it on manually
once. `android_layer.actions.open_settings("apps")` can jump the user
to a relevant settings screen to make this one-time step easier, but
JARVIS cannot skip it.

NEXT-SESSION IMPLEMENTATION PLAN (see HANDOVER.md for the full
checklist):
    1. Add `java_src/org/jarvis/jarvis/JarvisAccessibilityService.java`
       implementing AccessibilityService, forwarding onAccessibilityEvent
       payloads (window text tree) to Python over a local socket or
       python-for-android's existing JNI bridge.
    2. Add `android.add_src = java_src` to buildozer.spec.
    3. Add the <service> block + accessibility_service_config.xml to
       the manifest (buildozer.spec supports `android.manifest.intent_filters`
       and extra XML injection via `android.extra_manifest_xml`).
    4. Implement `AccessibilityUIController(IUIController)` below,
       reading from that socket/bridge instead of raising
       NotImplementedError.
    5. Register a "control_app" IActionExecutor in core/adapters.py
       (mirrors every other action -- no other Core file changes).

Until then, this class exists so calling code has a stable target to
import and so the Executor's registry can list "control_app" as a
recognized-but-not-yet-available action_type with a clear message,
instead of silently failing with "No executor registered".
"""

from core.interfaces import IUIController


class AccessibilityUIController(IUIController):
    def find_and_tap(self, label: str) -> bool:
        raise NotImplementedError(
            "Accessibility-based app control is not implemented in this MVP. "
            "See android_layer/accessibility.py for the next-session plan."
        )

    def type_text(self, text: str) -> bool:
        raise NotImplementedError(
            "Accessibility-based app control is not implemented in this MVP."
        )

    def read_screen(self) -> str:
        raise NotImplementedError(
            "Accessibility-based app control is not implemented in this MVP."
        )
